🆕feat(MASA.Try): Support loading js modules or css dynamically thru Settings window
masastack/MASA.Blazor pull request #1150
Opened 2023-03-28 06:38 UTC by msnoshain

# Description

Support loading js modules or css dynamically thru Settings window

2023-03-29 02:33 UTC, doddgu commented
@capdiem PTAL

2023-03-30 02:11 UTC, capdiem requested changes

2023-03-30 02:11 UTC, capdiem commented on src/Masa.Try.Shared/Pages/Index.razor
> +                <MButton Icon OnClick="()=>_settingModalOpened=true" XLarge @attributes="@context.Attrs">
加个`Class="mt-2"`

2023-03-30 02:13 UTC, capdiem commented
觉得不对劲，我们组件的script和css为什么要动态设置，直接在index.html里写好不就行了吗 😅 @doddgu

2023-04-05 12:13 UTC, merged