feat(docs): support relative url on document site
masastack/MASA.Blazor pull request #1188
Opened 2023-04-04 11:19 UTC by xyfy

2023-04-04 11:46 UTC, doddgu commented
@capdiem PTAL

2023-04-04 15:44 UTC, capdiem requested changes

2023-04-04 15:44 UTC, capdiem commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
> +      }
如果只是兼容不是`/`开头的相对路径，去改AppLink组件，而不是改这里。

2023-04-04 15:44 UTC, capdiem commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
> +        }
为了解决啥问题，要去拿域名？

2023-04-04 15:44 UTC, capdiem commented on docs/Masa.Docs.Shared/Shared/Toc.razor.cs
> +                _objRef = DotNetObjectReference.Create(this);
没用上吧

2023-04-04 15:44 UTC, capdiem commented on docs/Masa.Docs.Core/Components/AppLink.razor.cs
> +                    if (NavigationManager.ToUri().Host == uri.Host)
不惯着他们啊，以后该域名了咋整？让他们把文档里写了`https://docs.masastack.com`开头的全改掉。

2023-04-06 02:12 UTC, xyfy commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
> +      }
还兼容有些可能是跳转到具体的anchor的

2023-04-06 02:12 UTC, xyfy commented on docs/Masa.Docs.Shared/Shared/Toc.razor.cs
> +                _objRef = DotNetObjectReference.Create(this);
这个上次提交不小心删除了，现在补回来

2023-04-06 02:13 UTC, xyfy commented on docs/Masa.Docs.Core/Components/AppLink.razor.cs
> +                    if (NavigationManager.ToUri().Host == uri.Host)
支持下也好啊，我们文档审核的时候如果没有注意是可以进来的。就像你的不以/开头的都支持了

2023-04-06 02:14 UTC, xyfy commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
> +        }
拿了域名和相对路径进行拼接，得到url，然后直接得到hash

2023-04-06 05:27 UTC, capdiem commented on docs/Masa.Docs.Core/Components/AppLink.razor.cs
> +                    if (NavigationManager.ToUri().Host == uri.Host)
不建议兼容这种写法，判断是否是本站的链接还要去考虑外部设置的域名？兼容`/`写法是因为web本身支持这样写吧。

2023-04-06 05:28 UTC, capdiem commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
> +      }
我意思是把这逻辑放到AppLink组件里。

2023-04-06 05:34 UTC, xyfy commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
> +      }
针对  `/stack/abc#anchor`  这种，应该是前端进行渲染的吧？把anchor换掉

2023-04-06 07:42 UTC, capdiem requested changes

2023-04-06 07:42 UTC, capdiem commented on docs/Masa.Docs.Core/Components/AppLink.razor.cs
> +    }
```suggestion
    private bool IsExternal => Uri.TryCreate(Href, UriKind.Absolute, out var _);
```

2023-04-06 07:43 UTC, capdiem requested changes

2023-04-06 07:43 UTC, capdiem commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
> +      let nonAbsoluteUrl = true;
改成 isRelatedUrl

2023-04-06 08:06 UTC, capdiem approved these changes

2023-04-06 08:14 UTC, merged