docs: feat docs-compile
masastack/MASA.Blazor pull request #1241
Opened 2023-04-17 07:57 UTC by 239573049

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-04-19 07:02 UTC, doddgu commented
@capdiem PTAL

2023-04-20 11:43 UTC, capdiem requested changes

2023-04-20 11:43 UTC, capdiem commented on docs/Masa.Docs.Shared/Shared/CompileLayout.razor
> +@Body
```suggestion
<MApp>
    @Body
</MApp>
```

2023-04-20 11:56 UTC, capdiem requested changes

2023-04-20 11:56 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/DocumentCompile.razor
> +        background-color: #eee;
```suggestion
        background-color: white;
        padding: 24px;
```

2023-04-24 05:37 UTC, merged