📝 docs: Update the installation
masastack/MASA.Blazor pull request #1257
Opened 2023-04-21 03:13 UTC by capdiem

2023-04-21 09:00 UTC, doddgu requested changes

2023-04-21 09:06 UTC, capdiem commented on docs/Masa.Blazor.Docs/wwwroot/data/nav.json
> -      "layouts"
安装页有入口跳转到组件里的Application。特性里的Application就算是vueitfy2也不完整。跟进Vuetify3之后文档都会大改，那时在放回特性里也不迟。而且Application也包含App和Main组件的API，只能放在组件里。

2023-04-21 11:06 UTC, doddgu requested changes

2023-04-21 11:06 UTC, doddgu commented on docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/installation/zh-CN.md
> +dotnet new --install Masa.Template
Newest cli replace `--install` with `install`.

2023-04-21 11:06 UTC, doddgu commented on docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/installation/zh-CN.md
>  dotnet new masab -o MasaBlazorApp
masablazor-server

2023-04-21 11:06 UTC, doddgu commented on docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/installation/zh-CN.md
> +### 开始创造
If you want playful, it can write it like `开始创造你的奇迹吧`. Or normal like `从布局开始`, and link the `布局` to `Application` component doc.

2023-04-21 15:38 UTC, capdiem commented on docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/installation/zh-CN.md
> +### 开始创造
change to **Let's build** and **开始构建**

2023-04-23 03:56 UTC, doddgu approved these changes

2023-04-23 03:58 UTC, doddgu approved these changes

2023-04-23 03:58 UTC, merged