Supports dynamic editing preview of components
masastack/MASA.Blazor pull request #1455
Opened 2023-07-29 04:18 UTC by 239573049

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-07-31 15:47 UTC, capdiem requested changes

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
> +    private static bool _initialize;
static?

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
> +    [Inject] public IHttpClientFactory HttpClientFactory { get; set; }
```suggestion
    [Inject] public IHttpClientFactory HttpClientFactory { get; set; } = null!;
```

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
> +                    // var (razor, cs, css) = ResolveSourceCode(sourceCode);
```suggestion
```

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
> +    private static (string? Razor, string? cs, string? css) ResolveSourceCode(string sourceCode)
ResolveSourceCode 方法用不上了。

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor
目前想到的要做的功能：
1. 复制源码的功能
2. 编辑后重置代码的功能
3. 运行失败 Try catch
4. 运行按钮Loading效果

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Docs.Server/Program.cs
> +using Microsoft.AspNetCore.StaticFiles;
没有使用的using？

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
> +    private object options = new
```suggestion
    private object _options = new
```

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor
>                                  </MItemGroup>
不用MItemGroup 和 MItem 组件了。

2023-07-31 15:47 UTC, capdiem commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
> +        });
这里需要try catch吧，MFileInput示例会报错

2023-08-01 09:37 UTC, 239573049 commented on docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
> +    private static bool _initialize;
为了防止重复初始化。这个组件是多个渲染的，不适用static会导致重复加载程序集

2023-08-02 16:08 UTC, capdiem commented
@239573049 Server 模式下Run会报错欸

2023-08-03 12:48 UTC, capdiem approved these changes
Good job!

2023-08-03 12:48 UTC, merged