add init data and loadData event callback to be init
masastack/MASA.Blazor pull request #1786
Opened 2024-03-13 10:04 UTC by pigwing

# Description

因为当_drawflowProxy = await DrawflowJSModule.Init(ElementReference.GetSelector()!, _interopHandleReference, Mode);执行后,页面相关dom元素才会被渲染以及事件发生挂钩对接,若当有基础dataflow的json数据,这时候是无法初始化的,增加初始json数据参数以及loadData的event callback,协助初始化,不需要在first render的方法内进行delay.....等待相关dom渲染完成后再初始化控件的json数据..

2024-03-13 16:02 UTC, capdiem commented
@pigwing 在OnAfterRender里也要手动延迟吗？你提议的API有点冗余，如果一定需要，可以是一个 `Func<string>` 类型的参数。
```cs
[Parameter] public Func<string> DataInitializer { get; set; }
```

2024-03-14 01:24 UTC, pigwing commented
> @pigwing 在OnAfterRender里也要手动延迟吗？你提议的API有点冗余，如果一定需要，可以是一个 `Func<string>` 类型的参数。
> 
> ```cs
> [Parameter] public Func<string> DataInitializer { get; set; }
> ```

是的,因为在webview2里面呢,
options.RootComponents.RegisterCustomElement<CustomElement>("my-custom-element");
});
是不支持的,需要做
options.RootComponents.RegisterForJavaScript<CustomElement>("my-custom-element");
});
用JavaScript进行component渲染,要依赖dom节点,但因为组件们各自的firstRender时间不一致,会导致我页面的firstRender会比drawFlow要早,所以就需要delay一下等待drawFlow渲染完毕以后,再import出现相关的dataflow的dom,这时候才能去用js渲染对应的customer element.
![image](https://github.com/masastack/MASA.Blazor/assets/8393545/968f9258-836a-417c-97e0-124b784e95c8)
let targetElement = document.getElementById('quoteContainer');这块
https://learn.microsoft.com/zh-cn/aspnet/core/blazor/components/js-spa-frameworks?view=aspnetcore-8.0#render-razor-components-from-javascript

2024-03-14 02:58 UTC, pigwing commented
刚试了下.这样改还是有加载顺序的问题

2024-03-14 03:11 UTC, pigwing commented
OnImport在组件初始化的时候会被执行一次,这时候依然找不到相关的dom进行customer element渲染

2024-03-14 03:17 UTC, pigwing commented
> OnImport在组件初始化的时候会被执行一次,这时候依然找不到相关的dom进行customer element渲染

sorry,我错了,这样改就可以了.我测试通过了...

2024-03-14 04:02 UTC, capdiem requested changes
@pigwing

2024-03-14 04:02 UTC, capdiem commented on src/Masa.Blazor/Components/Drawflow/MDrawflow.cs
> +            }
不需要额外的 `_data` 变量吧。

```suggestion

            if (DataInitializer != null)
            {
                var data = await DataInitializer.Invoke();
                if (!string.IsNullOrWhitespace(data))
                {
                    await _drawflowProxy!.ImportAsync(_data);
                }
            }
```

2024-03-14 04:02 UTC, capdiem commented on src/Masa.Blazor/Components/Drawflow/MDrawflow.cs
> +
```suggestion
```

2024-03-14 04:17 UTC, pigwing commented on src/Masa.Blazor/Components/Drawflow/MDrawflow.cs
> +            }
是的,多余了

2024-03-15 08:17 UTC, capdiem commented
@pigwing 代码好像没有修改好？

2024-03-16 02:04 UTC, capdiem approved these changes
Thanks!

2024-03-16 02:07 UTC, merged